### ISSUE TITLE
번들링 필요 의문성 제기

### ISSUE THREAD

**Issue by ynifamily3** [Phryxia/AL-1S#11]
- 한 파일로 번들링할 필요가 없음. 오히려 빌드 타임만 늘어남.
- 의존 라이브러리 번들링은 더더욱 필요 없음. 라이브러리 내부에 ambiguous dependency가 있을 수 있어 에러가 발생하기도 하고, 속도도 더욱 느려짐.
- node로 바로 실행할 수 있을 정도로만 트랜스파일 하는 것이 좋을 것 같다.

**Comment by Phryxia** [comment]
음 그러면 `ts-node` 도입을 적극 검토해봅시다.

나중에 프로덕션 배포 시에만 `js`로 전수 빌드해서 `node`로 실행하고, 개발 환경에서는 `ts-node`에 `ts` 파일을 먹이면 될듯.
